<!DOCTYPE html>
<html lang="en">
<head>
    <title>
        Registration
    </title>
</head>
<body>
<div>
    <h1>Registration</h1>
</div>
<div>
    <form action="/registration" method="post">
        Login: <label><input type="text" name="username" aria-errormessage="Error"></label><br><br>
        Password: <label><input type="password" name="password"></label><br><br>
        First Name: <label><input type="text" name="firstName"></label><br><br>
        Surname: <label><input type="text" name="surname"></label><br><br>
        <label><input type="submit" value="Registration"></label>
    </form>
</div>
</body>
</html>